### ISSUE TITLE
Define a branch nomenclature as default

### ISSUE THREAD

**Issue by otaviojava** [ZupIT/charlescd-docs#5]
Currently, there is inconsistency in the default branch name.
It will be great if we have one default branch name between the open-source projects.

## `master`
* https://github.com/ZupIT/beagle
* https://github.com/ZupIT/docs-ritchie
* https://github.com/ZupIT/charlescd-docs
* https://github.com/ZupIT/horusec

## `main`
* https://github.com/ZupIT/charlescd
* https://github.com/ZupIT/ritchie-cli
* https://github.com/ZupIT/beagle-docs
* https://github.com/ZupIT/docs-horusec

It is vital to keep a nomenclature consistency among those open source projects.

## Task 

Once I believe those projects are going to move to the `main` branch instead of `master`. I've created the list here.

- [ ] [charlescd-docs](https://github.com/ZupIT/charlescd-docs/issues/5)
- [ ] [beagle](https://github.com/ZupIT/beagle/issues/1577)
- [x] [docs-ritchie](https://github.com/ZupIT/docs-ritchie/issues/85)
- [x] [horusec](https://github.com/ZupIT/horusec/issues/459)

**Comment by barbararochazup** [comment]
Hi @otaviojava 

Thanks for the suggestion :)

Today our documentation is migrating to another repo and charlescd-doc will be disabled. This new repository will have **main** as default branch.

These changes are expected to be completed by the end of this month (June 2021).
